from __future__ import annotations

import json

import pytest
from rdflib import Literal
from rdflib.namespace import RDF

from mvp.core import commission_graph
from mvp.core.cq_engine import (
    CQDraftService,
    CQEngineError,
    CommissionCQ,
    parse_commission_cq_markdown,
    validate_commission_expected,
)
from mvp.core.graph import BusinessGraphRepository
from mvp.core.llm.base import LLMProvider
from mvp.core.ontology_draft import DraftGenerationError, generate_commission_draft


class UnavailableProvider(LLMProvider):
    name = "test-unavailable"
    default_model = "none"

    def available(self) -> bool:
        return False

    def chat(self, prompt: str, **kwargs):
        raise AssertionError("chat should not be called when provider is unavailable")


class StaticProvider(LLMProvider):
    name = "test-static"
    default_model = "none"

    def __init__(self, response: str | None) -> None:
        self.response = response

    def available(self) -> bool:
        return True

    def chat(self, prompt: str, **kwargs) -> str | None:
        return self.response


def _provider_payload() -> dict[str, object]:
    return {
        "candidate_cqs": [{"id": "CQ-CT-900", "title": "Provider draft"}],
        "candidate_classes": [{"name": "CommissionOrder", "label": "Commission order"}],
        "candidate_relations": [{"name": "decomposesToTask", "domain": "TestProject", "range": "TestTask"}],
        "candidate_properties": [{"name": "taskStatus", "domain": "TestTask", "range": "xsd:string"}],
        "candidate_rules": [{"id": "provider_rule", "then": "Keep"}],
        "draft_turtle": "# ontology-id: commission-testing\n# provider draft\n",
        "draft_sparql_tests": ["CQ-CT-900"],
        "source_trace": [{"provider": "seed"}],
    }


def test_parse_commission_cq_markdown_reads_all_plan_cqs():
    questions = parse_commission_cq_markdown()

    assert [question.id for question in questions] == [
        "CQ-CT-001",
        "CQ-CT-002",
        "CQ-CT-003",
        "CQ-CT-004",
        "CQ-CT-005",
    ]
    assert questions[0].id == "CQ-CT-001"
    assert questions[0].title == "Which test projects belong to CO-2024-001?"
    assert questions[0].metadata["Intent"] == "commission_order_projects"
    assert questions[0].metadata["Source"] == "customer-demo"
    assert questions[0].metadata["Expected"] == "row_count=2, order_no=CO-2024-001"
    assert questions[0].expected == {"row_count": "2", "order_no": "CO-2024-001"}
    assert questions[0].evidence_fields == ["order_no", "project_id", "project_name"]
    assert questions[3].metadata["Intent"] == "standard_upgrade_flips"
    assert questions[3].expected["new_status"] == "Fail"
    assert "GRAPH <{{data_graph_iri}}>" in questions[3].sparql


def test_validate_commission_expected_checks_every_row_and_evidence_field():
    question = CommissionCQ(
        id="CQ-CT-900",
        title="Every row has the expected order",
        metadata={},
        sparql="SELECT * WHERE {}",
        expected={"row_count": "2", "order_no": "CO-2024-001"},
        evidence_fields=["order_no", "project_id"],
    )

    validate_commission_expected(
        question,
        [
            {"order_no": "CO-2024-001", "project_id": "P-001"},
            {"order_no": "CO-2024-001", "project_id": "P-002"},
        ],
    )
    with pytest.raises(AssertionError, match="row 2 expected order_no=CO-2024-001"):
        validate_commission_expected(
            question,
            [
                {"order_no": "CO-2024-001", "project_id": "P-001"},
                {"order_no": "WRONG", "project_id": "P-002"},
            ],
        )
    with pytest.raises(AssertionError, match="row 2 missing evidence field: project_id"):
        validate_commission_expected(
            question,
            [
                {"order_no": "CO-2024-001", "project_id": "P-001"},
                {"order_no": "CO-2024-001"},
            ],
        )


def test_parse_commission_cq_markdown_rejects_missing_required_metadata(tmp_path):
    cq_path = tmp_path / "commission-cqs.md"
    cq_path.write_text(
        """# Test

## CQ-CT-001 Missing field

- Business question: Why?
- Intent: something
- Source: test
- Covers: A, B
- Demo data: fixture
- Expected: row_count=1
```sparql
SELECT * WHERE {}
```

- Evidence fields: x
- Generated by: template
- Human review status: reviewed
""",
        encoding="utf-8",
    )

    with pytest.raises(CQEngineError, match="missing required field: Acceptance"):
        parse_commission_cq_markdown(cq_path)


def test_parse_commission_cq_markdown_requires_exactly_one_sparql_block(tmp_path):
    cq_path = tmp_path / "commission-cqs.md"
    cq_path.write_text(
        """# Test

## CQ-CT-001 Duplicate sparql

- Business question: Why?
- Intent: something
- Source: test
- Covers: A, B
- Demo data: fixture
- Expected: row_count=1
- Evidence fields: x
- Generated by: template
- Human review status: reviewed
- Acceptance: should work.

```sparql
SELECT * WHERE {}
```

```sparql
SELECT * WHERE {}
```
""",
        encoding="utf-8",
    )

    with pytest.raises(CQEngineError, match="must contain exactly one sparql code block"):
        parse_commission_cq_markdown(cq_path)


def test_template_only_generation_returns_reviewable_deterministic_draft():
    business_text = "Commission orders decompose projects into tasks and track standard upgrades."
    payload = generate_commission_draft(
        business_text=business_text,
        generation_mode="template_only",
    )

    assert payload["generation_mode"] == "template_only"
    assert [item["id"] for item in payload["candidate_cqs"]] == [
        "CQ-CT-001",
        "CQ-CT-002",
        "CQ-CT-003",
        "CQ-CT-004",
        "CQ-CT-005",
    ]
    assert payload["candidate_cqs"][0]["question"] == "Which test projects belong to CO-2024-001?"
    assert {item["name"] for item in payload["candidate_classes"]} >= {
        "CommissionOrder",
        "Product",
        "TestProject",
        "TestTask",
        "TestItem",
        "TestDataRecord",
        "PassCriterion",
        "StandardVersion",
        "JudgementResult",
        "ReevaluationImpact",
    }
    assert {item["name"] for item in payload["candidate_relations"]} >= {
        "hasProduct",
        "hasTestProject",
        "decomposesToTask",
        "supersedesStandard",
    }
    assert {item["name"] for item in payload["candidate_properties"]} >= {
        "taskStatus",
        "measuredValue",
        "threshold",
    }
    assert {item["id"] for item in payload["candidate_rules"]} >= {
        "decompose_project_to_task",
        "judge_less_equal_threshold",
        "mark_task_needs_review_on_flip",
    }
    assert "# ontology-id: commission-testing\n" in payload["draft_turtle"]
    assert "CommissionOrder" in payload["draft_turtle"]
    assert "decomposesToTask" in payload["draft_turtle"]
    assert "supersedesStandard" in payload["draft_turtle"]
    assert payload["draft_sparql_tests"] == ["CQ-CT-001", "CQ-CT-004"]
    assert payload["source_trace"][0] == {"generator": "template", "business_text": business_text}


def test_generate_commission_draft_rejects_invalid_generation_mode():
    with pytest.raises(DraftGenerationError, match="generation_mode must be one of"):
        generate_commission_draft(business_text="test", generation_mode="invalid")


def test_llm_only_requires_available_provider():
    with pytest.raises(DraftGenerationError, match="provider is required"):
        generate_commission_draft(business_text="test", generation_mode="llm_only")

    with pytest.raises(DraftGenerationError, match="provider is unavailable"):
        generate_commission_draft(
            business_text="test",
            generation_mode="llm_only",
            provider=UnavailableProvider(),
        )


def test_llm_only_raises_when_provider_json_is_invalid():
    with pytest.raises(DraftGenerationError, match="valid JSON"):
        generate_commission_draft(
            business_text="test",
            generation_mode="llm_only",
            provider=StaticProvider("not-json"),
        )


def test_llm_with_template_fallback_uses_template_when_provider_unavailable_or_invalid():
    unavailable = generate_commission_draft(
        business_text="test",
        generation_mode="llm_with_template_fallback",
        provider=UnavailableProvider(),
    )
    invalid = generate_commission_draft(
        business_text="test",
        generation_mode="llm_with_template_fallback",
        provider=StaticProvider(
            json.dumps(
                {
                    "candidate_cqs": [{"id": "CQ-CT-900", "title": "Old shape"}],
                    "candidate_classes": ["CommissionOrder"],
                    "candidate_relations": ["decomposesToTask"],
                    "candidate_properties": ["taskStatus"],
                    "candidate_rules": ["provider_rule"],
                    "draft_turtle": "# ontology-id: commission-testing\n",
                    "draft_sparql_tests": ["CQ-CT-900"],
                    "source_trace": [{"provider": "legacy"}],
                }
            )
        ),
    )

    assert unavailable["generation_mode"] == "llm_with_template_fallback"
    assert invalid["generation_mode"] == "llm_with_template_fallback"
    assert [item["id"] for item in unavailable["candidate_cqs"]] == [
        "CQ-CT-001",
        "CQ-CT-002",
        "CQ-CT-003",
        "CQ-CT-004",
        "CQ-CT-005",
    ]
    assert [item["id"] for item in invalid["candidate_cqs"]] == [
        "CQ-CT-001",
        "CQ-CT-002",
        "CQ-CT-003",
        "CQ-CT-004",
        "CQ-CT-005",
    ]
    assert unavailable["source_trace"][0]["generator"] == "template"
    assert invalid["source_trace"][0]["generator"] == "template"
    assert unavailable["source_trace"][-1]["reason"] == "provider unavailable"
    assert "candidate_classes[0] must be an object" in invalid["source_trace"][-1]["reason"]


def test_llm_with_template_fallback_uses_template_when_provider_response_is_not_json():
    payload = generate_commission_draft(
        business_text="test",
        generation_mode="llm_with_template_fallback",
        provider=StaticProvider("not-json"),
    )

    assert payload["generation_mode"] == "llm_with_template_fallback"
    assert payload["source_trace"][0]["generator"] == "template"
    assert "Expecting value" in payload["source_trace"][-1]["reason"]


def test_llm_generation_accepts_valid_provider_json():
    provider_payload = _provider_payload()

    payload = generate_commission_draft(
        business_text="test",
        generation_mode="llm_only",
        provider=StaticProvider(json.dumps(provider_payload)),
    )

    assert payload["generation_mode"] == "llm_only"
    assert payload["candidate_cqs"] == [{"id": "CQ-CT-900", "question": "Provider draft"}]
    assert payload["candidate_classes"] == provider_payload["candidate_classes"]
    assert payload["candidate_relations"] == provider_payload["candidate_relations"]
    assert payload["candidate_properties"] == provider_payload["candidate_properties"]
    assert payload["candidate_rules"] == provider_payload["candidate_rules"]
    assert payload["draft_turtle"] == provider_payload["draft_turtle"]
    assert payload["draft_sparql_tests"] == provider_payload["draft_sparql_tests"]
    assert payload["source_trace"][0] == {"provider": "seed"}
    assert payload["source_trace"][-1]["provider"] == "test-static"


def test_cq_draft_service_persists_lists_and_updates_status():
    repo = BusinessGraphRepository()
    repo.load_ontologies(reload=False)
    service = CQDraftService(repository=repo)
    payload = generate_commission_draft(
        business_text="Commission testing draft",
        generation_mode="template_only",
    )

    created = service.save_draft(payload)
    listing = service.list_drafts()
    updated = service.update_status(created["draft_id"], "reviewed")

    assert created["draft_id"] == "CQD-001"
    assert created["draft_status"] == "draft"
    assert created["payload"]["generation_mode"] == "template_only"
    assert listing == {
        "items": [
            {
                "draft_id": "CQD-001",
                "draft_status": "draft",
                "payload": payload,
            }
        ],
        "total": 1,
    }
    assert updated == {
        "draft_id": "CQD-001",
        "draft_status": "reviewed",
        "payload": payload,
    }
    assert service.list_drafts()["items"][0]["draft_status"] == "reviewed"

    data_graph = repo.graph(commission_graph.ONTOLOGY_ID, "data")
    draft_node = commission_graph._node("draft", "CQD-001")
    assert (draft_node, RDF.type, commission_graph.CTO.CQDraft) in data_graph
    assert Literal("reviewed") in data_graph.objects(draft_node, commission_graph.CTO.draftStatus)
    assert Literal(json.dumps(payload, ensure_ascii=False, sort_keys=True)) in data_graph.objects(
        draft_node,
        commission_graph.CTO.draftPayload,
    )


def test_cq_draft_service_rejects_invalid_status():
    repo = BusinessGraphRepository()
    repo.load_ontologies(reload=False)
    service = CQDraftService(repository=repo)
    created = service.save_draft(
        generate_commission_draft(business_text="Commission testing draft", generation_mode="template_only")
    )

    with pytest.raises(CQEngineError, match="invalid draft status"):
        service.update_status(created["draft_id"], "archived")


def test_cq_draft_service_lists_multiple_drafts_in_deterministic_id_order():
    repo = BusinessGraphRepository()
    repo.load_ontologies(reload=False)
    service = CQDraftService(repository=repo)

    service.save_draft(generate_commission_draft(business_text="draft one", generation_mode="template_only"))
    service.save_draft(generate_commission_draft(business_text="draft two", generation_mode="template_only"))

    listing = service.list_drafts()

    assert [item["draft_id"] for item in listing["items"]] == ["CQD-001", "CQD-002"]
