"""Commission-testing CQ parsing and draft lifecycle support."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import shutil
from typing import Any

from rdflib import Literal, URIRef
from rdflib.namespace import RDF

from mvp.core import commission_graph, graph
from mvp.core.cq_workflow import CQWorkflowError, validate_draft_quality_gate
from mvp.core.graph import BusinessGraphRepository


@dataclass(frozen=True)
class CommissionCQ:
    id: str
    title: str
    metadata: dict[str, str]
    sparql: str
    expected: dict[str, str]
    evidence_fields: list[str]


@dataclass(frozen=True)
class CommissionCQRunResult:
    question: CommissionCQ
    rows: list[dict[str, Any]]


class CQEngineError(ValueError):
    """Raised when commission CQ metadata or draft lifecycle rules are violated."""


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CQ_PATH = Path("docs/cq/commission-testing-cqs.md")
DEFAULT_RELEASE_ROOT = PROJECT_ROOT / "runtime" / "cq-releases"
REQUIRED_METADATA_FIELDS = (
    "Business question",
    "Intent",
    "Source",
    "Covers",
    "Demo data",
    "Expected",
    "Evidence fields",
    "Generated by",
    "Human review status",
    "Acceptance",
)
VALID_DRAFT_STATUSES = {"draft", "reviewed", "published", "rejected"}
SECTION_RE = re.compile(r"^##\s+(CQ-CT-\d{3})\s+(.+?)\s*$", re.MULTILINE)
SPARQL_RE = re.compile(r"```sparql\s*\n(.*?)\n```", re.DOTALL | re.IGNORECASE)
_METADATA_KEY_PATTERN = "|".join(re.escape(field) for field in REQUIRED_METADATA_FIELDS)
METADATA_RE = re.compile(
    rf"-\s+(?P<key>{_METADATA_KEY_PATTERN}):\s*(?P<value>.*?)(?=(?:\s+-\s+(?:{_METADATA_KEY_PATTERN}):)|\s*\Z)",
    re.DOTALL,
)


def parse_commission_cq_markdown(path: str | Path = DEFAULT_CQ_PATH) -> list[CommissionCQ]:
    """Parse commission-testing CQ markdown into executable CQ records."""

    cq_path = Path(path)
    text = cq_path.read_text(encoding="utf-8")
    matches = list(SECTION_RE.finditer(text))
    if not matches:
        raise CQEngineError(f"{cq_path} contains no CQ-CT sections")

    questions: list[CommissionCQ] = []
    seen: set[str] = set()
    for index, match in enumerate(matches):
        cq_id = match.group(1)
        title = match.group(2).strip()
        body_start = match.end()
        body_end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        body = text[body_start:body_end]

        if cq_id in seen:
            raise CQEngineError(f"duplicate CQ id: {cq_id}")
        seen.add(cq_id)

        metadata = _parse_metadata(cq_id, body)
        sparql = _parse_sparql(cq_id, body)
        expected = _parse_expected(cq_id, metadata["Expected"])
        evidence_fields = _parse_csv_field(metadata["Evidence fields"])
        if not evidence_fields:
            raise CQEngineError(f"{cq_id} Evidence fields must not be empty")

        questions.append(
            CommissionCQ(
                id=cq_id,
                title=title,
                metadata=metadata,
                sparql=sparql,
                expected=expected,
                evidence_fields=evidence_fields,
            )
        )
    return questions


class CQDraftService:
    """Persist reviewable CQ drafts in the commission-testing data graph."""

    def __init__(
        self,
        *,
        repository: BusinessGraphRepository | None = None,
        ontology_id: str = commission_graph.ONTOLOGY_ID,
        release_root: str | Path | None = None,
    ) -> None:
        self.repository = repository or BusinessGraphRepository()
        self.ontology_id = ontology_id
        self.release_root = Path(release_root).resolve() if release_root is not None else DEFAULT_RELEASE_ROOT

    def save_draft(self, payload: dict[str, Any]) -> dict[str, Any]:
        validate_draft_payload(payload)
        serialized = _serialize_payload(payload)
        data_graph = self.repository.graph(self.ontology_id, "data")
        draft_id = self._next_draft_id(data_graph)
        draft_node = commission_graph._node("draft", draft_id)
        data_graph.add((draft_node, RDF.type, commission_graph.CTO.CQDraft))
        data_graph.set((draft_node, commission_graph.CTO.localId, Literal(draft_id)))
        data_graph.set((draft_node, commission_graph.CTO.draftStatus, Literal("draft")))
        data_graph.set((draft_node, commission_graph.CTO.draftPayload, Literal(serialized)))
        self._sync()
        return {"draft_id": draft_id, "draft_status": "draft", "payload": json.loads(serialized)}

    def list_drafts(self) -> dict[str, Any]:
        data_graph = self.repository.graph(self.ontology_id, "data")
        items = [self._serialize_draft(data_graph, node) for node in self._draft_nodes(data_graph)]
        return {"items": items, "total": len(items)}

    def list_releases(self) -> dict[str, Any]:
        items = self._release_manifests()
        return {"items": items, "total": len(items)}

    def update_status(self, draft_id: str, draft_status: str) -> dict[str, Any]:
        if draft_status not in VALID_DRAFT_STATUSES:
            raise CQEngineError(f"invalid draft status: {draft_status}")
        return self.update_draft(draft_id, draft_status=draft_status)

    def update_draft(
        self,
        draft_id: str,
        *,
        draft_status: str | None = None,
        payload: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        if draft_status is None and payload is None:
            raise CQEngineError("draft update must include draft_status or payload")
        if draft_status is not None and draft_status not in VALID_DRAFT_STATUSES:
            raise CQEngineError(f"invalid draft status: {draft_status}")
        if draft_status == "published":
            raise CQEngineError("drafts must be published through the publish endpoint")
        data_graph = self.repository.graph(self.ontology_id, "data")
        draft_node = self._find_draft_node(data_graph, draft_id)
        if draft_node is None:
            raise CQEngineError(f"draft not found: {draft_id}")
        current = self._serialize_draft(data_graph, draft_node)
        if current["draft_status"] == "published":
            raise CQEngineError("published draft cannot be modified")
        if payload is not None:
            validate_draft_payload(payload)
        if draft_status is not None:
            data_graph.set((draft_node, commission_graph.CTO.draftStatus, Literal(draft_status)))
        if payload is not None:
            data_graph.set((draft_node, commission_graph.CTO.draftPayload, Literal(_serialize_payload(payload))))
        self._sync()
        return self._serialize_draft(data_graph, draft_node)

    def publish_draft(self, draft_id: str) -> dict[str, Any]:
        data_graph = self.repository.graph(self.ontology_id, "data")
        draft_node = self._find_draft_node(data_graph, draft_id)
        if draft_node is None:
            raise CQEngineError(f"draft not found: {draft_id}")
        draft = self._serialize_draft(data_graph, draft_node)
        if draft["draft_status"] != "reviewed":
            raise CQEngineError("draft must be reviewed before publish")
        validate_draft_payload(draft["payload"])
        try:
            quality_gate = validate_draft_quality_gate(draft["payload"])
        except CQWorkflowError as exc:
            raise CQEngineError(str(exc)) from exc
        exports = self._export_payload(draft["payload"])
        release = self._build_release_manifest(draft["draft_id"], exports, quality_gate)
        self._write_release(release, exports)
        data_graph.set((draft_node, commission_graph.CTO.draftStatus, Literal("published")))
        try:
            self._sync()
        except Exception:
            data_graph.set((draft_node, commission_graph.CTO.draftStatus, Literal("reviewed")))
            self._delete_release(release)
            raise
        published = self._serialize_draft(data_graph, draft_node)
        published["exports"] = exports
        published["release"] = release
        return published

    def _draft_nodes(self, data_graph) -> list[URIRef]:
        nodes = [node for node in data_graph.subjects(RDF.type, commission_graph.CTO.CQDraft) if isinstance(node, URIRef)]
        return sorted(nodes, key=lambda node: _literal_text(data_graph, node, commission_graph.CTO.localId))

    def _next_draft_id(self, data_graph) -> str:
        highest = 0
        for node in self._draft_nodes(data_graph):
            draft_id = _literal_text(data_graph, node, commission_graph.CTO.localId)
            try:
                highest = max(highest, int(draft_id.split("-", 1)[1]))
            except (IndexError, ValueError):
                continue
        return f"CQD-{highest + 1:03d}"

    def _find_draft_node(self, data_graph, draft_id: str) -> URIRef | None:
        for node in data_graph.subjects(commission_graph.CTO.localId, Literal(draft_id)):
            if isinstance(node, URIRef) and (node, RDF.type, commission_graph.CTO.CQDraft) in data_graph:
                return node
        return None

    def _serialize_draft(self, data_graph, draft_node: URIRef) -> dict[str, Any]:
        payload_text = _literal_text(data_graph, draft_node, commission_graph.CTO.draftPayload)
        try:
            payload = json.loads(payload_text)
        except json.JSONDecodeError as exc:
            draft_id = _literal_text(data_graph, draft_node, commission_graph.CTO.localId)
            raise CQEngineError(f"stored draft payload is invalid JSON: {draft_id}") from exc
        draft = {
            "draft_id": _literal_text(data_graph, draft_node, commission_graph.CTO.localId),
            "draft_status": _literal_text(data_graph, draft_node, commission_graph.CTO.draftStatus),
            "payload": payload,
        }
        if draft["draft_status"] == "published":
            draft["exports"] = self._export_payload(payload)
            try:
                release = self._latest_release_for_draft(draft["draft_id"])
            except CQEngineError:
                release = None
            if release is not None:
                draft["release"] = release
        return draft

    def _export_payload(self, payload: dict[str, Any]) -> dict[str, Any]:
        return {
            "ontology_id": self.ontology_id,
            "draft_turtle": str(payload.get("draft_turtle") or ""),
            "candidate_cqs": list(payload.get("candidate_cqs") or []),
            "candidate_rules": list(payload.get("candidate_rules") or []),
            "draft_sparql_tests": list(payload.get("draft_sparql_tests") or []),
        }

    def _sync(self) -> None:
        self.repository._sync_graph_to_remote(self.ontology_id, "data")

    def _build_release_manifest(
        self,
        draft_id: str,
        exports: dict[str, Any],
        quality_gate: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        release_number = self._next_release_number()
        release_id = f"CQR-{release_number:03d}"
        release_dir = self.release_root / self.ontology_id / release_id
        turtle_path = release_dir / "draft.ttl"
        rules_path = release_dir / "candidate-rules.json"
        sparql_path = release_dir / "sparql-tests.json"
        manifest_path = release_dir / "manifest.json"

        release = {
            "release_id": release_id,
            "version": f"v{release_number}",
            "draft_id": draft_id,
            "ontology_id": self.ontology_id,
            "published_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "quality_gate": quality_gate or {"passed": False, "checks": []},
            "files": {
                "manifest": _display_path(manifest_path),
                "draft_turtle": _display_path(turtle_path),
                "candidate_rules": _display_path(rules_path),
                "draft_sparql_tests": _display_path(sparql_path),
            },
        }
        return release

    def _write_release(self, release: dict[str, Any], exports: dict[str, Any]) -> None:
        release_id = str(release["release_id"])
        release_dir = self.release_root / self.ontology_id / release_id
        tmp_dir = self.release_root / self.ontology_id / f".{release_id}.tmp"
        try:
            if tmp_dir.exists():
                shutil.rmtree(tmp_dir)
            tmp_dir.mkdir(parents=True)
            (tmp_dir / "draft.ttl").write_text(str(exports["draft_turtle"]), encoding="utf-8")
            (tmp_dir / "candidate-rules.json").write_text(
                json.dumps(exports["candidate_rules"], ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            (tmp_dir / "sparql-tests.json").write_text(
                json.dumps(exports["draft_sparql_tests"], ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            (tmp_dir / "manifest.json").write_text(
                json.dumps(release, ensure_ascii=False, indent=2, sort_keys=True),
                encoding="utf-8",
            )
            if release_dir.exists():
                raise CQEngineError(f"release directory already exists: {release_dir}")
            tmp_dir.replace(release_dir)
        except OSError as exc:
            raise CQEngineError(f"release files could not be written: {exc}") from exc
        finally:
            if tmp_dir.exists():
                shutil.rmtree(tmp_dir)

    def _delete_release(self, release: dict[str, Any]) -> None:
        release_dir = self.release_root / self.ontology_id / str(release["release_id"])
        if release_dir.exists():
            shutil.rmtree(release_dir)

    def _next_release_number(self) -> int:
        highest = 0
        release_dir = self.release_root / self.ontology_id
        if release_dir.exists():
            for path in release_dir.glob("CQR-*"):
                if not path.is_dir():
                    continue
                try:
                    highest = max(highest, int(path.name.split("-", 1)[1]))
                except (IndexError, ValueError):
                    continue
        return highest + 1

    def _release_manifests(self) -> list[dict[str, Any]]:
        release_dir = self.release_root / self.ontology_id
        if not release_dir.exists():
            return []
        items: list[dict[str, Any]] = []
        for manifest_path in release_dir.glob("CQR-*/manifest.json"):
            try:
                manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                raise CQEngineError(f"release manifest is unreadable: {manifest_path}") from exc
            self._validate_release_manifest(manifest, manifest_path)
            items.append(manifest)
        return sorted(items, key=_release_sort_key)

    def _latest_release_for_draft(self, draft_id: str) -> dict[str, Any] | None:
        matches = [release for release in self._release_manifests() if release.get("draft_id") == draft_id]
        return matches[-1] if matches else None

    def _validate_release_manifest(self, manifest: Any, manifest_path: Path) -> None:
        if not isinstance(manifest, dict):
            raise CQEngineError(f"release manifest is invalid: {manifest_path}")
        required = {"release_id", "version", "draft_id", "ontology_id", "published_at", "files"}
        if not required.issubset(manifest):
            raise CQEngineError(f"release manifest is invalid: {manifest_path}")
        files = manifest.get("files")
        required_files = {"manifest", "draft_turtle", "candidate_rules", "draft_sparql_tests"}
        if not isinstance(files, dict) or not required_files.issubset(files):
            raise CQEngineError(f"release manifest is invalid: {manifest_path}")


class CommissionCQRunner:
    def __init__(
        self,
        *,
        repository: BusinessGraphRepository,
        ontology_id: str = "commission-testing",
    ) -> None:
        self.repository = repository
        self.ontology_id = ontology_id

    def run_question(self, question: CommissionCQ) -> CommissionCQRunResult:
        rows = self._select_rows(render_commission_sparql(question, self.ontology_id))
        validate_commission_expected(question, rows)
        return CommissionCQRunResult(question=question, rows=rows)

    def _select_rows(self, sparql: str) -> list[dict[str, Any]]:
        if self.repository.client is None:
            raise RuntimeError("CommissionCQRunner requires a repository with a Fuseki client")
        return [
            {str(key): normalize_sparql_value(value) for key, value in row.items()}
            for row in self.repository.client.select(sparql)
        ]


def _parse_metadata(cq_id: str, body: str) -> dict[str, str]:
    metadata_text = SPARQL_RE.sub("", body)
    metadata: dict[str, str] = {}
    for match in METADATA_RE.finditer(metadata_text):
        key = match.group("key").strip()
        value = " ".join(match.group("value").split())
        metadata[key] = value
    for field in REQUIRED_METADATA_FIELDS:
        if field not in metadata or not metadata[field]:
            raise CQEngineError(f"{cq_id} missing required field: {field}")
    return metadata


def _parse_sparql(cq_id: str, body: str) -> str:
    blocks = [block.strip() for block in SPARQL_RE.findall(body)]
    if len(blocks) != 1:
        raise CQEngineError(f"{cq_id} must contain exactly one sparql code block")
    return blocks[0]


def _parse_expected(cq_id: str, raw: str) -> dict[str, str]:
    expected: dict[str, str] = {}
    for item in _parse_csv_field(raw):
        if "=" not in item:
            raise CQEngineError(f"{cq_id} invalid Expected assertion: {item}")
        key, value = [part.strip() for part in item.split("=", 1)]
        if not key or not value:
            raise CQEngineError(f"{cq_id} invalid Expected assertion: {item}")
        expected[key] = value
    if "row_count" not in expected:
        raise CQEngineError(f"{cq_id} missing Expected assertion: row_count")
    return expected


def _parse_csv_field(raw: str) -> list[str]:
    return [item.strip() for item in raw.split(",") if item.strip()]


def render_commission_sparql(question: CommissionCQ | str, ontology_id: str) -> str:
    sparql = question.sparql if isinstance(question, CommissionCQ) else str(question)
    return sparql.replace("{{data_graph_iri}}", graph.graph_iri(ontology_id, "data"))


def normalize_sparql_value(value: Any) -> Any:
    if isinstance(value, dict) and "value" in value:
        return value["value"]
    return value


def validate_commission_expected(question: CommissionCQ, rows: list[dict[str, Any]]) -> None:
    expected_count = int(question.expected["row_count"])
    if len(rows) != expected_count:
        raise AssertionError(f"{question.id} expected {expected_count} rows, got {len(rows)}")
    for index, row in enumerate(rows, start=1):
        for field in question.evidence_fields:
            if field not in row:
                raise AssertionError(f"{question.id} row {index} missing evidence field: {field}")
        for key, expected in question.expected.items():
            if key == "row_count":
                continue
            actual = row.get(key)
            if str(actual) != expected:
                raise AssertionError(f"{question.id} row {index} expected {key}={expected}, got {actual}")


def _serialize_payload(payload: dict[str, Any]) -> str:
    try:
        return json.dumps(payload, ensure_ascii=False, sort_keys=True)
    except TypeError as exc:
        raise CQEngineError("draft payload must be JSON serializable") from exc


def validate_draft_payload(payload: dict[str, Any]) -> None:
    if not isinstance(payload, dict):
        raise CQEngineError("draft payload must be a JSON object")

    required_types = {
        "draft_turtle": str,
        "candidate_cqs": list,
        "candidate_rules": list,
        "draft_sparql_tests": list,
    }
    for field, expected_type in required_types.items():
        if field not in payload:
            raise CQEngineError(f"draft payload missing required field: {field}")
        if not isinstance(payload[field], expected_type):
            expected_name = "list" if expected_type is list else "string"
            raise CQEngineError(f"draft payload field {field} must be {expected_name}")
    if not payload["draft_turtle"].strip():
        raise CQEngineError("draft payload field draft_turtle must not be empty")


def _literal_text(data_graph, subject: URIRef, predicate) -> str:
    obj = next(data_graph.objects(subject, predicate), None)
    return str(obj) if obj is not None else ""


def _display_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(Path.cwd().resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _release_sort_key(release: dict[str, Any]) -> tuple[int, int | str]:
    release_id = str(release.get("release_id") or "")
    try:
        return (0, int(release_id.split("-", 1)[1]))
    except (IndexError, ValueError):
        return (1, release_id)
