"""Commission-testing CQ parsing and draft lifecycle support."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re
from typing import Any

from rdflib import Literal, URIRef
from rdflib.namespace import RDF

from mvp.core import commission_graph
from mvp.core.graph import BusinessGraphRepository


@dataclass(frozen=True)
class CommissionCQ:
    id: str
    title: str
    metadata: dict[str, str]
    sparql: str
    expected: dict[str, str]
    evidence_fields: list[str]


class CQEngineError(ValueError):
    """Raised when commission CQ metadata or draft lifecycle rules are violated."""


DEFAULT_CQ_PATH = Path("docs/cq/commission-testing-cqs.md")
REQUIRED_METADATA_FIELDS = (
    "Business question",
    "Intent",
    "Source",
    "Covers",
    "Demo data",
    "Expected",
    "Evidence fields",
    "Generated by",
    "Human review status",
    "Acceptance",
)
VALID_DRAFT_STATUSES = {"draft", "reviewed", "published", "rejected"}
SECTION_RE = re.compile(r"^##\s+(CQ-CT-\d{3})\s+(.+?)\s*$", re.MULTILINE)
SPARQL_RE = re.compile(r"```sparql\s*\n(.*?)\n```", re.DOTALL | re.IGNORECASE)
_METADATA_KEY_PATTERN = "|".join(re.escape(field) for field in REQUIRED_METADATA_FIELDS)
METADATA_RE = re.compile(
    rf"-\s+(?P<key>{_METADATA_KEY_PATTERN}):\s*(?P<value>.*?)(?=(?:\s+-\s+(?:{_METADATA_KEY_PATTERN}):)|\s*\Z)",
    re.DOTALL,
)


def parse_commission_cq_markdown(path: str | Path = DEFAULT_CQ_PATH) -> list[CommissionCQ]:
    """Parse commission-testing CQ markdown into executable CQ records."""

    cq_path = Path(path)
    text = cq_path.read_text(encoding="utf-8")
    matches = list(SECTION_RE.finditer(text))
    if not matches:
        raise CQEngineError(f"{cq_path} contains no CQ-CT sections")

    questions: list[CommissionCQ] = []
    seen: set[str] = set()
    for index, match in enumerate(matches):
        cq_id = match.group(1)
        title = match.group(2).strip()
        body_start = match.end()
        body_end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        body = text[body_start:body_end]

        if cq_id in seen:
            raise CQEngineError(f"duplicate CQ id: {cq_id}")
        seen.add(cq_id)

        metadata = _parse_metadata(cq_id, body)
        sparql = _parse_sparql(cq_id, body)
        expected = _parse_expected(cq_id, metadata["Expected"])
        evidence_fields = _parse_csv_field(metadata["Evidence fields"])
        if not evidence_fields:
            raise CQEngineError(f"{cq_id} Evidence fields must not be empty")

        questions.append(
            CommissionCQ(
                id=cq_id,
                title=title,
                metadata=metadata,
                sparql=sparql,
                expected=expected,
                evidence_fields=evidence_fields,
            )
        )
    return questions


class CQDraftService:
    """Persist reviewable CQ drafts in the commission-testing data graph."""

    def __init__(
        self,
        *,
        repository: BusinessGraphRepository | None = None,
        ontology_id: str = commission_graph.ONTOLOGY_ID,
    ) -> None:
        self.repository = repository or BusinessGraphRepository()
        self.ontology_id = ontology_id

    def save_draft(self, payload: dict[str, Any]) -> dict[str, Any]:
        serialized = _serialize_payload(payload)
        data_graph = self.repository.graph(self.ontology_id, "data")
        draft_id = self._next_draft_id(data_graph)
        draft_node = commission_graph._node("draft", draft_id)
        data_graph.add((draft_node, RDF.type, commission_graph.CTO.CQDraft))
        data_graph.set((draft_node, commission_graph.CTO.localId, Literal(draft_id)))
        data_graph.set((draft_node, commission_graph.CTO.draftStatus, Literal("draft")))
        data_graph.set((draft_node, commission_graph.CTO.draftPayload, Literal(serialized)))
        self._sync()
        return {"draft_id": draft_id, "draft_status": "draft", "payload": json.loads(serialized)}

    def list_drafts(self) -> dict[str, Any]:
        data_graph = self.repository.graph(self.ontology_id, "data")
        items = [self._serialize_draft(data_graph, node) for node in self._draft_nodes(data_graph)]
        return {"items": items, "total": len(items)}

    def update_status(self, draft_id: str, draft_status: str) -> dict[str, Any]:
        if draft_status not in VALID_DRAFT_STATUSES:
            raise CQEngineError(f"invalid draft status: {draft_status}")
        data_graph = self.repository.graph(self.ontology_id, "data")
        draft_node = self._find_draft_node(data_graph, draft_id)
        if draft_node is None:
            raise CQEngineError(f"draft not found: {draft_id}")
        data_graph.set((draft_node, commission_graph.CTO.draftStatus, Literal(draft_status)))
        self._sync()
        return self._serialize_draft(data_graph, draft_node)

    def _draft_nodes(self, data_graph) -> list[URIRef]:
        nodes = [node for node in data_graph.subjects(RDF.type, commission_graph.CTO.CQDraft) if isinstance(node, URIRef)]
        return sorted(nodes, key=lambda node: _literal_text(data_graph, node, commission_graph.CTO.localId))

    def _next_draft_id(self, data_graph) -> str:
        highest = 0
        for node in self._draft_nodes(data_graph):
            draft_id = _literal_text(data_graph, node, commission_graph.CTO.localId)
            try:
                highest = max(highest, int(draft_id.split("-", 1)[1]))
            except (IndexError, ValueError):
                continue
        return f"CQD-{highest + 1:03d}"

    def _find_draft_node(self, data_graph, draft_id: str) -> URIRef | None:
        for node in data_graph.subjects(commission_graph.CTO.localId, Literal(draft_id)):
            if isinstance(node, URIRef) and (node, RDF.type, commission_graph.CTO.CQDraft) in data_graph:
                return node
        return None

    def _serialize_draft(self, data_graph, draft_node: URIRef) -> dict[str, Any]:
        payload_text = _literal_text(data_graph, draft_node, commission_graph.CTO.draftPayload)
        try:
            payload = json.loads(payload_text)
        except json.JSONDecodeError as exc:
            draft_id = _literal_text(data_graph, draft_node, commission_graph.CTO.localId)
            raise CQEngineError(f"stored draft payload is invalid JSON: {draft_id}") from exc
        return {
            "draft_id": _literal_text(data_graph, draft_node, commission_graph.CTO.localId),
            "draft_status": _literal_text(data_graph, draft_node, commission_graph.CTO.draftStatus),
            "payload": payload,
        }

    def _sync(self) -> None:
        self.repository._sync_graph_to_remote(self.ontology_id, "data")


def _parse_metadata(cq_id: str, body: str) -> dict[str, str]:
    metadata_text = SPARQL_RE.sub("", body)
    metadata: dict[str, str] = {}
    for match in METADATA_RE.finditer(metadata_text):
        key = match.group("key").strip()
        value = " ".join(match.group("value").split())
        metadata[key] = value
    for field in REQUIRED_METADATA_FIELDS:
        if field not in metadata or not metadata[field]:
            raise CQEngineError(f"{cq_id} missing required field: {field}")
    return metadata


def _parse_sparql(cq_id: str, body: str) -> str:
    blocks = [block.strip() for block in SPARQL_RE.findall(body)]
    if len(blocks) != 1:
        raise CQEngineError(f"{cq_id} must contain exactly one sparql code block")
    return blocks[0]


def _parse_expected(cq_id: str, raw: str) -> dict[str, str]:
    expected: dict[str, str] = {}
    for item in _parse_csv_field(raw):
        if "=" not in item:
            raise CQEngineError(f"{cq_id} invalid Expected assertion: {item}")
        key, value = [part.strip() for part in item.split("=", 1)]
        if not key or not value:
            raise CQEngineError(f"{cq_id} invalid Expected assertion: {item}")
        expected[key] = value
    if "row_count" not in expected:
        raise CQEngineError(f"{cq_id} missing Expected assertion: row_count")
    return expected


def _parse_csv_field(raw: str) -> list[str]:
    return [item.strip() for item in raw.split(",") if item.strip()]


def _serialize_payload(payload: dict[str, Any]) -> str:
    try:
        return json.dumps(payload, ensure_ascii=False, sort_keys=True)
    except TypeError as exc:
        raise CQEngineError("draft payload must be JSON serializable") from exc


def _literal_text(data_graph, subject: URIRef, predicate) -> str:
    obj = next(data_graph.objects(subject, predicate), None)
    return str(obj) if obj is not None else ""
